apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: 864899837235.dkr.ecr.ap-south-1.amazonaws.com/sandilya/myrepo
        ports:
        - containerPort: 80
